import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Alexis about page",
    description: "Generated by create next app",
};

export default function AboutPage() {
    return (
        <span className="text-7xl">About page</span>        
    );
}